baseURL = "https://jeffyuhaoliu.github.io/"
languageCode = "en-us"
title = "Mundane Notes"
theme = "ananke"
themesDir = "./themes"
# relativeURLs = true

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/images/itswednesday.jpg"